<a href="https://colab.research.google.com/github/ukpaiuj2014-commits/Applying-statistics-and-core-data-science-techniques-in-business./blob/main/Bag_of_Words_Demonstration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Bag-of-Words representation

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer


In [2]:
docs = [
        'This is the first project.',
        'This project is the second project., the project is nice',
        'And this is the third one.',
        'Is this the first project?', ]

In [3]:
vectorizer = CountVectorizer(analyzer = "word",
                             lowercase=True,
                             max_features = 50)

In [4]:
# Convert the documents into a document-term matrix.
wm = vectorizer.fit_transform(docs)
print(wm.todense())

[[0 1 1 0 0 1 0 1 0 1]
 [0 0 2 1 0 3 1 2 0 1]
 [1 0 1 0 1 0 0 1 1 1]
 [0 1 1 0 0 1 0 1 0 1]]


Words tranformed in alphabetical order.

In [5]:
vocabulary = vectorizer.vocabulary_
print(vocabulary)

{'this': np.int64(9), 'is': np.int64(2), 'the': np.int64(7), 'first': np.int64(1), 'project': np.int64(5), 'second': np.int64(6), 'nice': np.int64(3), 'and': np.int64(0), 'third': np.int64(8), 'one': np.int64(4)}


Index of each word is highlighted

In [6]:
tokens = vectorizer.get_feature_names_out()
print(tokens)

['and' 'first' 'is' 'nice' 'one' 'project' 'second' 'the' 'third' 'this']


Each word highlighted according to their index, following their alphabetical order

In [7]:
# Create an index for each row.
doc_names = ['Doc{:d}'.format(idx) for idx, _ in enumerate(wm)]
df_bow = pd.DataFrame(data=wm.toarray(), index=doc_names,
                  columns=tokens)

In [8]:
df_bow

,and,first,is,nice,one,project,second,the,third,this
Doc0,0,1,1,0,0,1,0,1,0,1
Doc1,0,0,2,1,0,3,1,2,0,1
Doc2,1,0,1,0,1,0,0,1,1,1
Doc3,0,1,1,0,0,1,0,1,0,1


The documents showing the number of times each of the words appear in each of the documents.